// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Type      string             `json:"type"`
	Name      string             `json:"name"`
	Path      string             `json:"path"`
	MimeType  *string            `json:"mime_type"`
	SizeBytes *int64             `json:"size_bytes"`
	Checksum  *string            `json:"checksum"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	WorkflowID  string             `json:"workflow_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Phase       *string            `json:"phase"`
	Status      *string            `json:"status"`
	Config      []byte             `json:"config"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   *bool              `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Plan      *string            `json:"plan"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	Name          *string            `json:"name"`
	Role          *string            `json:"role"`
	EmailVerified *bool              `json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
