// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects SET status = 'archived' WHERE id = $1
`

func (q *Queries) ArchiveProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveProject, id)
	return err
}

const cleanupExpiredTokens = `-- name: CleanupExpiredTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < NOW() OR revoked = TRUE
`

func (q *Queries) CleanupExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredTokens)
	return err
}

const countProjectsByTenant = `-- name: CountProjectsByTenant :one
SELECT COUNT(*) FROM projects WHERE tenant_id = $1 AND status != 'archived'
`

func (q *Queries) CountProjectsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (project_id, tenant_id, type, name, path, mime_type, size_bytes, checksum, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, tenant_id, type, name, path, mime_type, size_bytes, checksum, metadata, created_at
`

type CreateArtifactParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Type      string      `json:"type"`
	Name      string      `json:"name"`
	Path      string      `json:"path"`
	MimeType  *string     `json:"mime_type"`
	SizeBytes *int64      `json:"size_bytes"`
	Checksum  *string     `json:"checksum"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ProjectID,
		arg.TenantID,
		arg.Type,
		arg.Name,
		arg.Path,
		arg.MimeType,
		arg.SizeBytes,
		arg.Checksum,
		arg.Metadata,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Path,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, workflow_id, name, description, config, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, workflow_id, name, description, phase, status, config, created_by, created_at, updated_at
`

type CreateProjectParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	WorkflowID  string      `json:"workflow_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Config      []byte      `json:"config"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TenantID,
		arg.WorkflowID,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.Name,
		&i.Description,
		&i.Phase,
		&i.Status,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked, created_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, plan, settings)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, plan, settings, created_at, updated_at
`

type CreateTenantParams struct {
	Name     string  `json:"name"`
	Slug     string  `json:"slug"`
	Plan     *string `json:"plan"`
	Settings []byte  `json:"settings"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.Settings,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, name, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, email, password_hash, name, role, email_verified, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         *string     `json:"name"`
	Role         *string     `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifact, id)
	return err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, project_id, tenant_id, type, name, path, mime_type, size_bytes, checksum, metadata, created_at FROM artifacts WHERE id = $1
`

func (q *Queries) GetArtifactByID(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByID, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TenantID,
		&i.Type,
		&i.Name,
		&i.Path,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, tenant_id, workflow_id, name, description, phase, status, config, created_by, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.Name,
		&i.Description,
		&i.Phase,
		&i.Status,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByWorkflowID = `-- name: GetProjectByWorkflowID :one
SELECT id, tenant_id, workflow_id, name, description, phase, status, config, created_by, created_at, updated_at FROM projects WHERE workflow_id = $1
`

func (q *Queries) GetProjectByWorkflowID(ctx context.Context, workflowID string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByWorkflowID, workflowID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowID,
		&i.Name,
		&i.Description,
		&i.Phase,
		&i.Status,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked, created_at FROM refresh_tokens
WHERE token_hash = $1 AND NOT revoked AND expires_at > NOW()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, plan, settings, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, plan, settings, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, name, role, email_verified, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, name, role, email_verified, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTenantAndEmail = `-- name: GetUserByTenantAndEmail :one
SELECT id, tenant_id, email, password_hash, name, role, email_verified, last_login_at, created_at, updated_at FROM users WHERE tenant_id = $1 AND email = $2
`

type GetUserByTenantAndEmailParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

func (q *Queries) GetUserByTenantAndEmail(ctx context.Context, arg GetUserByTenantAndEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTenantAndEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactsByProject = `-- name: ListArtifactsByProject :many
SELECT id, project_id, tenant_id, type, name, path, mime_type, size_bytes, checksum, metadata, created_at FROM artifacts
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListArtifactsByProject(ctx context.Context, projectID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TenantID,
			&i.Type,
			&i.Name,
			&i.Path,
			&i.MimeType,
			&i.SizeBytes,
			&i.Checksum,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByProjectAndType = `-- name: ListArtifactsByProjectAndType :many
SELECT id, project_id, tenant_id, type, name, path, mime_type, size_bytes, checksum, metadata, created_at FROM artifacts
WHERE project_id = $1 AND type = $2
ORDER BY created_at DESC
`

type ListArtifactsByProjectAndTypeParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Type      string      `json:"type"`
}

func (q *Queries) ListArtifactsByProjectAndType(ctx context.Context, arg ListArtifactsByProjectAndTypeParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByProjectAndType, arg.ProjectID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TenantID,
			&i.Type,
			&i.Name,
			&i.Path,
			&i.MimeType,
			&i.SizeBytes,
			&i.Checksum,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTenant = `-- name: ListProjectsByTenant :many
SELECT id, tenant_id, workflow_id, name, description, phase, status, config, created_by, created_at, updated_at FROM projects
WHERE tenant_id = $1 AND status != 'archived'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListProjectsByTenant(ctx context.Context, arg ListProjectsByTenantParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowID,
			&i.Name,
			&i.Description,
			&i.Phase,
			&i.Status,
			&i.Config,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, tenant_id, workflow_id, name, description, phase, status, config, created_by, created_at, updated_at FROM projects
WHERE created_by = $1 AND status != 'archived'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByUserParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListProjectsByUser(ctx context.Context, arg ListProjectsByUserParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowID,
			&i.Name,
			&i.Description,
			&i.Phase,
			&i.Status,
			&i.Config,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, email, password_hash, name, role, email_verified, last_login_at, created_at, updated_at FROM users WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE user_id = $1
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateProjectPhase = `-- name: UpdateProjectPhase :exec
UPDATE projects SET phase = $2 WHERE id = $1
`

type UpdateProjectPhaseParams struct {
	ID    pgtype.UUID `json:"id"`
	Phase *string     `json:"phase"`
}

func (q *Queries) UpdateProjectPhase(ctx context.Context, arg UpdateProjectPhaseParams) error {
	_, err := q.db.Exec(ctx, updateProjectPhase, arg.ID, arg.Phase)
	return err
}

const updateProjectPhaseByWorkflowID = `-- name: UpdateProjectPhaseByWorkflowID :exec
UPDATE projects SET phase = $2, updated_at = NOW() WHERE workflow_id = $1
`

type UpdateProjectPhaseByWorkflowIDParams struct {
	WorkflowID string  `json:"workflow_id"`
	Phase      *string `json:"phase"`
}

func (q *Queries) UpdateProjectPhaseByWorkflowID(ctx context.Context, arg UpdateProjectPhaseByWorkflowIDParams) error {
	_, err := q.db.Exec(ctx, updateProjectPhaseByWorkflowID, arg.WorkflowID, arg.Phase)
	return err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :exec
UPDATE projects SET status = $2 WHERE id = $1
`

type UpdateProjectStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status *string     `json:"status"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error {
	_, err := q.db.Exec(ctx, updateProjectStatus, arg.ID, arg.Status)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET name = $2, plan = $3, settings = $4
WHERE id = $1
RETURNING id, name, slug, plan, settings, created_at, updated_at
`

type UpdateTenantParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Plan     *string     `json:"plan"`
	Settings []byte      `json:"settings"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Plan,
		arg.Settings,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
